version: '3'
services:
    nginx:
        image: nginx
        ports:
            - "8090:80"
        links:
            - php-fpm
        volumes:
            - ./www:/var/www/html
            - ./nginx/sites:/etc/nginx/sites-enabled
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        command: ["nginx",'-g','daemon off;']
    php-fpm:
        image: 'bitnami/php-fpm:7.0'
        volumes:
            - ./www:/var/www/html
            - ./php/:/bitnami/php/conf/
        links:
            - mysql
            - redis
    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: hanxiao666.
        volumes:
            - ./mysql:/var/lib/mysql
    redis:
        image: redis
